export default function Head() {
  return (
    <>
      <title>2023년 2월 앱테크 순위</title>

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
