export default function Head() {
  return (
    <>
      <title>2023년 2월 앱테크 순위</title>
      <meta
        name="description"
        content="2023년 2월 앱테크 순위를 확인해보세요. 퀴즈, 미션, 만보기, 클릭 등 다양한 방법으로 적립금을 쌓을 수 있는 앱테크를 확인해보세요. 토스 행운퀴즈, OK캐쉬백 오퀴즈, 정답을 확인해보세요."
      />

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
